<html>
  <head>
    <title>Fiqhuency</title>
  </head>
  <body>
    <h1>Fiqhuency</h1>
    <nav>
      <a><button>Home</button></a>
      <a><button>Forum</button></a>
      <a><button>Scroll</button></a>
    </nav>
  </body>
</html>
